server:
  port: 8080

eureka:
  instance:
    # ESTO ES LO QUE FALTA:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

        - id: product-service
          uri: lb://product-service # <--- Corregido (antes decía service-product)
          predicates:
            - Path=/products/**

        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**