server:
  port: 8093
  error:
    include-message: always

spring:
  application:
    name: shopping-service

  datasource:
    url: jdbc:mysql://localhost:3306/shopping_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # Usa 'update' si quieres que Spring cree las tablas solo
    properties:
      hibernate:
        format_sql: true

  # Aquí metemos la configuración de Feign dentro del mismo bloque spring
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always